name: scrap_bid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  shared_preferences: 2.0.5
  auto_size_text: 2.1.0
  google_fonts: 2.0.0
  get: 4.1.3
  firebase_core: ^1.0.4
  firebase_messaging: ^9.1.2
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.2
  device_info: ^2.0.0
  cached_network_image: ^3.0.0
  flutter_local_notifications: ^5.0.0+1
  fab_circular_menu: ^1.0.2
  font_awesome_flutter: ^9.0.0
  flutter_native_splash: 1.1.8+4
  carousel_slider: 3.0.0
  change_app_package_name: 1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

